#!/bin/bash

VOLUME_INFO=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
VOLUME=$(echo "$VOLUME_INFO" | awk '{print $2*100}')

if echo "$VOLUME_INFO" | grep -q "[MUTED]"; then
  ICON="󰝟 "
elif [[ $VOLUME -ge 50 ]]; then
  ICON="󰕾 "
elif [[ $VOLUME -lt 50 ]] && [[ $VOLUME -gt 0 ]]; then
  ICON="󰖀 "
elif [[ $VOLUME -eq 0 ]]; then
  ICON="󰕿 "
fi

echo "$ICON$VOLUME%"
